https://github.com/wavefy/decentralized-llm-inference-runner
https://github.com/Weminal-labs/Weball/tree/dev
https://github.com/weminal-labs/weball-contract
https://github.com/Weminal-labs/ActionsX-BE
https://github.com/Weminal-labs/ActionX-Extension
https://github.com/Weminal-labs/actionx-nft-minting
https://github.com/0xBoji/aptos-bounty
https://github.com/0xBoji/shaker-game
https://github.com/0xBoji/move-vietnam/tree/main/aptos-move-spider-vn
https://github.dev/0xBoji/simple-randomness-game
https://github.com/0xBoji/examples-aptos-dao
https://github.com/0xBoji/aptos-ai
https://github.com/hiephtdev/module_marketplace
https://github.com/hocptit/AI-Trading-aptos
https://github.com/eragon-gg/eragon
https://github.com/phuquiivo03/meme-throwing.git
https://github.com/Aptos-NFT-Lending/nft-lending-sc
https://github.com/0xLSTx/multi_pool
https://github.com/ayushagarwal27/aptos_pokemon_vault
https://github.com/phapdev/randomness-game
https://github.com/FromSunNews/staking-aptos-contract
https://github.com/FromSunNews/voting-contract/tree/main
https://github.com/FromSunNews/sui-interface-demo
https://github.com/lochoang174/Aptous-smart-contract
https://github.com/tuvuanh27/aptos-move-voting
https://github.com/hoangtien47/actionx-nft-minting
https://github.com/mainguyen85/in-game-coin-swap-v2
https://github.com/buinhien5/aptos-token-staking
https://github.com/alfredalfie123/move_multisender
github.com/chithien25/demo-project-nft-marketplace
github.com/chithiendo/AptosQuantum-fungible-asset-voting
github.com/cuongpham42334/AptosNexus-telegram-boilerplate-template-with-mizu-core
github.com/dotham654/apts-project-test-hello-aptos-telegram-click-game
github.com/duynencute11/AptosNova-billboard
github.com/hoangduc19867/apts-project-aptos-token-staking
github.com/hoanglananh111/project-test-hello-taxed-fungible-asset
github.com/hoangminhcong001/aptos-project-test-telegram-boilerplate-template
github.com/hoangnam1123g/apts-project-multidex-router
github.com/hoangnam34243/aptos-project-dutch-auction
github.com/hoangquyet112/AptosStellar-hello_blockchain
github.com/honganh1253/AptosNova-surf-for-type-safety
github.com/honghien123/aptos-surf-for-type-safety
github.com/hungnguyen3424/project-test-telegram-boilerplate-template-with-mizu-core
github.com/huyle32423/demo-project-test-aptos-token-mint
github.com/khanhphuong32234/new-project-test-hello-v1-aptos-token-staking
github.com/linhanhnguyenn/demo-project-test-fungible-asset-voting
github.com/linhlinh00/demo-project-test-v1-aptos-boilerplate
github.com/linhlinhtran/AptosMirage-aptos-token-mint
github.com/linhphuongtran/demo-project-test-nft-launchpad
github.com/maianhhbao1234/new-project-test-hello-aptos-telegram-click-game
github.com/maianhtra/AptosQuantum-taxed-fungible-asset
github.com/mainamanh11/aptos-project-test-hello-billboard
github.com/minhanhnguyenn/AptosElysium-aptos-token-staking
github.com/minhlinhdo/apt-aptos-token-mint
github.com/namnguyen000/project-test-hello-v1-todo
github.com/namnguyen321265/new-project-test-hello-v1-taxed-fungible-asset
github.com/nguyenninh12/AptosNexus-aptos-token-staking
github.com/phuonglinhdo/AptosCelestial-fungible-asset-voting
github.com/phuongthaodo12/AptosCelestial-taxed-fungible-asset
github.com/phuongthaodoo/aptos-project-test-fungible-asset-voting
github.com/quanganhtran11/aptos-billboard
github.com/quynhmaido/new-project-test-hello-todo
github.com/quynhnam13/new-project-test-hello-v1-hello_blockchain
github.com/thamdo2k/demo-project-test-fungible-asset-launchpad
github.com/thaothao23423/project-aptos-token-mint
github.com/tiepbeo222/project-test-surf-for-type-safety
github.com/tiepbeo3211/new-project-test-hello-v1-aptos-telegram-click-game
github.com/tiepbeo999/project-test-surf-for-type-safety
github.com/tiepbeobro/AptosStellar-aptos-token-mint
github.com/tiepnghien2213/apts-project-test-fungible-asset-launchpad
github.com/tuantu19/aptos-taxed-fungible-asset
github.com/tungbeo2225/aptos-project-todo
github.com/tungbeo6789/apts-project-aptos-token-staking
github.com/tungbeooii21/project-test-hello-v1-aptos-token-mint
github.com/tungbeoooo23/AptosQuantum-todo
github.com/tungbeoooo232/aptos-aptos-token-staking
github.com/tungboio234/project-test-hello-v1-telegram-boilerplate-template-with-mizu-core
github.com/tungngu345/new-project-test-hello-v1-dutch-auction